name: buildwithdocker-on-push

on:
  push:

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true # use buildx as default build
      - name: Create build dir
        run: mkdir -p build
#      - name: pwd
#        run: pwd
#      - name: env
#        run: env
      - name: Compile for linux/arm64
        # see https://github.com/docker/buildx/blob/master/docs/reference/buildx_build.md#output this allows that all files created by docker are written somewhere
        run: docker build . --platform linux/arm64 -o type=local,dest=build/arm64 && cd build/arm64/usr/src/app && tar -czf $GITHUB_WORKSPACE/build/sdmon-musl-arm64.tar.gz sdmon
#      - name: Compile for linux/armv7
#        # see https://github.com/docker/buildx/blob/master/docs/reference/buildx_build.md#output this allows that all files created by docker are written somewhere
#        run: docker build . --platform linux/arm64 -o type=local,dest=build/armv7 && cd build/armv7/usr/src/app && tar -czf $GITHUB_WORKSPACE/build/sdmon-musl-armv7.tar.gz sdmon
#      - name: Check result
#        # see https://github.com/docker/buildx/blob/master/docs/reference/buildx_build.md#output this allows that all files created by docker are written somewhere
#        run: ls -ltrR dockerbuildoutput
      - name: Release if tagged
        if: ${{startsWith(github.ref, 'refs/tags/v')}} # tags start with v see https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            build/sdmon-musl-arm64.tar.gz
            build/sdmon-musl-armv7.tar.gz
        id: "automatic_releases_tagged"
      - name: Release if prerelease
        if: ${{startsWith(github.ref, 'refs/heads/master')}} # branch master and ignore any tag see https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            build/sdmon-musl-arm64.tar.gz
            build/sdmon-musl-armv7.tar.gz
        id: "automatic_releases_not_tagged"